# Generated by Django 4.0.4 on 2022-04-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_continued', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continueduser',
            old_name='location_id',
            new_name='location',
        ),
    ]
