# Generated by Django 4.0.4 on 2022-04-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_continued', '0002_rename_location_id_continueduser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continueduser',
            name='age',
            field=models.IntegerField(),
        ),
    ]
