# Generated by Django 4.0.4 on 2022-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_continued', '0003_alter_continueduser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continueduser',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
