# Generated by Django 4.0.4 on 2022-04-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_continued', '0004_alter_continueduser_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continueduser',
            options={'verbose_name': 'Доп. поля пользователя', 'verbose_name_plural': 'Доп. поля пользователей'},
        ),
        migrations.AlterModelOptions(
            name='locationuser',
            options={'verbose_name': 'Местоположения пользователя', 'verbose_name_plural': 'Местоположения пользователей'},
        ),
    ]
