# Generated by Django 4.0.4 on 2022-05-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='data_create',
            new_name='create_at',
        ),
    ]
