# Generated by Django 4.0.4 on 2022-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
