# Generated by Django 4.0.4 on 2022-05-09 19:30

from django.db import migrations

from ads.models import Characteristics


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Characteristics = apps.get_model('ads', 'Characteristics')
    for char in Characteristics.objects.all():
        char.slug = '%s %s' % (char.name, char.pk)
        char.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_characteristics_slug'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
