# Generated by Django 4.0.4 on 2022-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20220509_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='slug',
            field=models.SlugField(max_length=10),
        ),
    ]
