# Generated by Django 4.0.4 on 2022-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_characteristics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='slug',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
