# Generated by Django 4.0.4 on 2022-05-09 19:53

from django.db import migrations
from transliterate import translit

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Person = apps.get_model("authentication", "User")
    db_alias = schema_editor.connection.alias
    for person in Person.objects.all():
        person.email = '%s@gmail.com' % (person.username,)
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_age'),
    ]

    operations = [
        migrations.RunPython(forwards_func,),
    ]
