# Generated by Django 4.0.4 on 2022-05-09 20:09
from datetime import datetime

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Person = apps.get_model("authentication", "User")
    db_alias = schema_editor.connection.alias
    for person, t in enumerate(Person.objects.all()):
        person.birth_date = datetime.date(2000, 1, 1)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RunPython(forwards_func, ),
    ]
